# Generated by Django 2.2.24 on 2023-05-19 16:38

from django.db import migrations

def connect_owner_apartments(apps, shcema_epitor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner_name=owner.name)
        owner.apartments.set(flats)
        owner.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230519_1838'),
    ]

    operations = [
        migrations.RunPython(connect_owner_apartments)
    ]
